spring.application.name=1-security-pro-inmemory-basic-auth

#stable version of springboot 2.7.6

#embedded server 
server.port=4444

#view resolver config
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp